#!/bin/bash

# --- Configuration ---
ENV_FILE=".env"
# API URLs to be written to the .env file (production endpoints)
# Change these URLs if needed, if you are trying on local development servers,
# replace them with:
# NEXT_PUBLIC_TENANT_API_URL="http://localhost:8000/tenants"
# NEXT_PUBLIC_USER_API_URL="http://localhost:8000/users"
# NEXT_PUBLIC_CATEGORY_API_URL="http://localhost:8000/categories"
# NEXT_PUBLIC_RESOURCE_API_URL="http://localhost:8000/resources"
# NEXT_PUBLIC_BOOKING_API_URL="http://localhost:8000/bookings"

NEXT_PUBLIC_TENANT_API_URL="https://tenant-service-production-b057.up.railway.app"
NEXT_PUBLIC_USER_API_URL="https://user-service-production-6b5a.up.railway.app"
NEXT_PUBLIC_RESOURCE_API_URL="https://resource-service-production-c44a.up.railway.app"
NEXT_PUBLIC_BOOKING_API_URL="https://booking-service-production-4d90.up.railway.app"
# The desired Node.js version (adjust if needed)
NODE_VERSION="18"

# --- Functions ---

# Function to check the exit status of the last command
check_status() {
    if [ $? -ne 0 ]; then
        echo -e "\n❌ ERROR: $1 failed. Exiting script."
        exit 1
    fi
}

# Function to install Node.js using Node Version Manager (NVM)
install_nodejs() {
    echo -e "\n--- 1. Installing Node.js (v${NODE_VERSION}) and npm using NVM ---"

    # Check if curl is installed (needed for NVM installation)
    if ! command -v curl &> /dev/null; then
        echo "Curl is not installed. Attempting to install curl..."
        if command -v apt-get &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y curl
        elif command -v yum &> /dev/null; then
            sudo yum install -y curl
        elif command -v brew &> /dev/null; then
            brew install curl
        else
            echo "Cannot install curl automatically. Please install curl and re-run."
            exit 1
        fi
        check_status "Curl installation"
    fi

    # Install NVM if not already installed
    if ! command -v nvm &> /dev/null; then
        echo "Installing NVM..."
        # Install NVM using the official script (latest version)
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
        check_status "NVM installation"

        # Source NVM to make it available in the current shell
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
        echo "NVM installed successfully."
    fi

    # Install the specified Node.js version
    nvm install "$NODE_VERSION"
    check_status "Node.js v${NODE_VERSION} installation"
    nvm use "$NODE_VERSION"
    check_status "Switching to Node.js v${NODE_VERSION}"
    echo "✅ Node.js $(node -v) and npm $(npm -v) installed."
}

# Function to install Yarn
install_yarn() {
    echo -e "\n--- 2. Installing Yarn ---"
    # Yarn is typically installed globally via npm
    npm install -g yarn
    check_status "Yarn global installation"
    echo "✅ Yarn $(yarn -v) installed."
}

# Function to create the .env file
create_env_file() {
    echo -e "\n--- 3. Creating $ENV_FILE file ---"

    cat << EOF > $ENV_FILE
#
# Generated by the project setup script
#

NEXT_PUBLIC_TENANT_API_URL=$NEXT_PUBLIC_TENANT_API_URL
NEXT_PUBLIC_USER_API_URL=$NEXT_PUBLIC_USER_API_URL
NEXT_PUBLIC_RESOURCE_API_URL=$NEXT_PUBLIC_RESOURCE_API_URL
NEXT_PUBLIC_BOOKING_API_URL=$NEXT_PUBLIC_BOOKING_API_URL

EOF

    check_status "Creating $ENV_FILE"
    echo "✅ $ENV_FILE created successfully with API configurations."
}

# Function to run project commands
run_project_commands() {
    echo -e "\n--- 4. Running Project Commands (yarn install, build, start) ---"

    echo "Running 'yarn install'..."
    yarn install
    check_status "'yarn install'"

    echo "Running 'yarn build'..."
    yarn build
    check_status "'yarn build'"

    echo "Running 'yarn start'..."
    yarn start &
    # We use '&' to run 'yarn start' in the background so the script can finish
    # You may remove '&' if you want the script to wait for the server to stop.

    echo -e "\n✅ All project commands executed."
    echo "🚀 Your Next.js application should now be running in the background."
    echo "   (Check your browser, usually at http://localhost:3000)"
}

# --- Main Script Execution ---

echo "=========================================="
echo "      🚀 Next.js Project Setup Script     "
echo "=========================================="

# 1. Install Node.js and npm
install_nodejs

# 2. Install Yarn
install_yarn

# 3. Create .env file
create_env_file

# 4. Run project commands
run_project_commands

echo -e "\n=========================================="
echo "🎉 Setup Complete!"
echo "=========================================="
echo "To view logs, run 'fg' or check your process list."

exit 0